application: ciniicoauthornetwork
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers: 
- url: /stylesheets 
  static_dir: stylesheets 
- url: /bootstrap 
  static_dir: bootstrap 
- url: .*
  script: main.app


libraries:
- name: webapp2
  version: "2.5.2"
